<#
Patch Fox on Windows to use the local modified client script.

This script will:
- Detect the currently-executed `fox` command location.
- If it's a script (.py, .ps1, .bat, .cmd) it will back it up and replace it with a wrapper
  that calls your local repository's `client/fox.py` (non-destructive backup is created).
- If it's an .exe (typical when installed via pip/wheels), it will create a user-level
  wrapper directory (under %USERPROFILE%\fox-repl), create `fox.bat` there that calls
  the local `client/fox.py`, and prepend that directory to your user PATH so the wrapper
  is found first.

Usage (PowerShell as your user):
  1. Open PowerShell as your normal user (not Administrator) where you want the change.
  2. Run: `.	ools\patch_fox_windows.ps1`
  3. When prompted, enter the full path to your local FoxNest repo (or press Enter to use
     the current directory). The script will show actions and ask to continue.

Note: Modifying PATH is a user-level change. You may need to restart your shell (or log out)
for PATH changes to take effect in new terminals.
#>

param()

function Write-Info($m){ Write-Host $m -ForegroundColor Cyan }
function Write-Warn($m){ Write-Host $m -ForegroundColor Yellow }
function Write-Err($m){ Write-Host $m -ForegroundColor Red }

Write-Info "Detecting installed 'fox' command..."
$cmd = Get-Command fox -ErrorAction SilentlyContinue
if (-not $cmd) {
    Write-Warn "No 'fox' command found on PATH. This script can still create a wrapper."
}

$repoPath = Read-Host "Enter full path to local FoxNest repo (press Enter to use current directory)"
if ([string]::IsNullOrWhiteSpace($repoPath)) { $repoPath = (Get-Location).Path }

if (-not (Test-Path $repoPath)) {
    Write-Err "Provided repo path does not exist: $repoPath"
    exit 1
}

$localClient = Join-Path $repoPath 'client\fox.py'
if (-not (Test-Path $localClient)) {
    $localClient = Join-Path $repoPath 'client\client1\fox.py'
    if (-not (Test-Path $localClient)) {
        Write-Err "Could not find client/fox.py or client/client1/fox.py under the repo path: $repoPath"
        exit 1
    }
}

Write-Info "Local client found: $localClient"

if ($cmd) {
    $foxPath = $cmd.Source
    Write-Info "Detected 'fox' at: $foxPath"
    $ext = [IO.Path]::GetExtension($foxPath).ToLower()

    $backupPath = "$foxPath.backup.$((Get-Date).ToString('yyyyMMddHHmmss'))"
    Write-Info "Backup path: $backupPath"

    if ($ext -in '.py','.ps1','.bat','.cmd','.txt') {
        Write-Info "Detected script file. Backing up original and installing wrapper."
        Copy-Item -Path $foxPath -Destination $backupPath -Force

        $wrapperContent = @"
@echo off
REM Wrapper generated by patch_fox_windows.ps1 - forwards to local Fox client
python "%localClient%" %*
"@"
        # replace placeholder with actual localClient path (escaped)
        $wrapperContent = $wrapperContent -replace '%localClient%', ($localClient -replace '\\','\\\\')

        Set-Content -Path $foxPath -Value $wrapperContent -Encoding ASCII
        Write-Info "Replaced $foxPath with wrapper that calls local client. Original backed up to $backupPath"
        exit 0
    }

    # If exe or other binary, create user wrapper dir and add to PATH
    Write-Info "Detected binary executable (extension: $ext). Creating user wrapper to shadow it."
}
else {
    Write-Info "No existing 'fox' command found — creating user wrapper that will act as 'fox'."
}

$wrapperDir = Join-Path $env:USERPROFILE 'fox-repl'
New-Item -ItemType Directory -Force -Path $wrapperDir | Out-Null

$batPath = Join-Path $wrapperDir 'fox.bat'
$batContent = "@echo off`r`npython \"$localClient\" %*"
Set-Content -Path $batPath -Value $batContent -Encoding ASCII

Write-Info "Created wrapper: $batPath"

# Ensure wrapperDir is at the front of user PATH
$currentUserPath = [Environment]::GetEnvironmentVariable('PATH', 'User')
if (-not $currentUserPath) { $currentUserPath = '' }
if ($currentUserPath -notlike "*$wrapperDir*") {
    $newPath = "$wrapperDir;$currentUserPath"
    [Environment]::SetEnvironmentVariable('PATH', $newPath, 'User')
    Write-Info "Prepended $wrapperDir to user PATH."
    Write-Info "You may need to start a new PowerShell window for the change to take effect."
} else {
    Write-Info "$wrapperDir already in user PATH."
}

Write-Info "Done. Test by opening a new PowerShell and running: fox --help"
